CREATE TABLE seller
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP,
    CONSTRAINT uk_seller_phone_number UNIQUE (phone_number)
);

CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    price       DECIMAL(19, 2) NOT NULL,
    seller_id   BIGINT         NOT NULL,
    stock       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP      NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_product_seller FOREIGN KEY (seller_id) REFERENCES seller (id)
);

CREATE TABLE tb_order
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id    BIGINT         NOT NULL,
    order_code   VARCHAR(36)    NOT NULL,
    amount       DECIMAL(19, 2) NOT NULL,
    customer_id  BIGINT         NOT NULL,
    order_status VARCHAR(20)    NOT NULL,
    created_at   TIMESTAMP      NOT NULL,
    updated_at   TIMESTAMP,
    CONSTRAINT fk_tb_order_seller FOREIGN KEY (seller_id) REFERENCES seller (id),
    CONSTRAINT chk_tb_order_amount CHECK (amount > 0)
);

CREATE TABLE item_order
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT         NOT NULL,
    product_id BIGINT         NOT NULL,
    quantity   INT            NOT NULL,
    sub_amount DECIMAL(19, 2) NOT NULL,
    created_at TIMESTAMP      NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_item_order_order FOREIGN KEY (order_id) REFERENCES tb_order (id),
    CONSTRAINT fk_item_order_product FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT chk_item_order_quantity CHECK (quantity > 0)
);
